### ISSUE TITLE
[Question] Issues with wechat_assets_picker

### ISSUE THREAD

**Issue by AlexV525** [YeFei572/yefei572.github.io#1]
你好，我是 `wechat_assets_picker` 的作者。

有看到你针对 package 的文章，想麻烦你展开说一下哪个部分有问题？

https://github.com/YeFei572/yefei572.github.io/blob/main/_posts/2021-11-19-flutter2.5.x%E4%BD%BF%E7%94%A8wechat_assets_picker%E6%8F%92%E4%BB%B6%E7%9A%84%E5%B7%A8%E5%9D%91%E5%84%BF.md

**Comment by YeFei572** [comment]
你好，之前的吐槽文章了，当时项目本来准备集成这个库的，但是集成过程中并不顺利，各种报错，然后写笔记记录一下，后面用的是别的库。

如果文章对你产生困扰，我修改一下。

**Comment by AlexV525** [comment]
那我根据你的文章内容补充两点，同时希望你回答我一个疑问。

## 补充
- Kotlin 问题是因为 `photo_manager` 是原生 plugin，你的项目使用的版本过旧，这点我有在 https://github.com/fluttercandies/flutter_photo_manager/issues/561 中提供解决方案，但是没有链接到 picker。
- 卡在 `assembleDebug` 与使用了什么库无关，仅仅与你当前的开发环境的网络有关。
- MultiDex 与使用了什么库无关，仅仅与当前你的项目 dex 方法数超过了限制有关，此处由于 `photo_manager` 有较多的方法，所以表现为引用即报错。

以上三点补充在 Flutter 2.10 版本中均为默认或可自动修复的选项，此处我认为可能与你的项目生不逢时有关，另外你可能对这类知识并没有一定程度的认知，希望我的补充对你的知识体系有一定的完善。

## 疑问
什么叫 **一会这一会那，对开发者非常不友好，各种刁难**？我比较好奇这一点，希望能够解释清楚。

**Comment by YeFei572** [comment]
是的， 我用词不当，已经修改了。给你添麻烦了。
